# Makefile for lab1
#
#

all: lab1p1 lab1p2 lab1p4

lab1p1: lab1p1.cpp
	g++ --std=c++0x lab1p1.cpp -o lab1p1

lab1p2: lab1p2.cpp
	g++ --std=c++0x lab1p2.cpp -o lab1p2

lab1p4: lab1p4.cpp
	g++ --std=c++0x lab1p4.cpp -o lab1p4

clean:
	rm -f lab1p1 lab1p2 lab1p4 *~
