# Makefile for lab5
#
#

all: lab5p1 lab5p2

lab5p1: shape_main.cpp Shape.cpp
	g++ -std=c++0x shape_main.cpp Shape.cpp -o lab5p1

lab5p2: poly_main.cpp Polynomial.cpp
	g++ -std=c++0x poly_main.cpp Polynomial.cpp -o lab5p2

clean:
	rm -f lab5p1 lab5p2 *~
